### ISSUE TITLE
[Known issue] Android 14 or later may failed in getting current wallpaper on your device

### ISSUE THREAD

**Issue by ZoeMeow941** [ZoeMeow941/DutSchedule#19]
**Describe the bug**
(Please read in `To Reporduce` selection)

**To Reproduce**
- Google is restricted for getting current wallpaper on Android 14 or later. So, if you like to use `Your current wallpaper` option on this OS, we're sorry, this option won't work anymore.
- IssueTracker: https://issuetracker.google.com/issues/237124750
- Article source: https://www.xda-developers.com/android-14-has-a-wallpaper-problem/

**Screenshots**
(no information)

**Device (please complete the following information):**

- Device: Any Android device
- OS: Android 14 or later
- App version: 2.0-draft11

**Additional context**
(no more information)

**Comment by ZoeMeow1027** [comment]
Commit in https://github.com/ZoeMeow1027/DutSchedule/commit/48de4df1eecd3bf2244b1f670f5ba8684d467bc4 might fixed this issue. Need additional re-check.

**Comment by ZoeMeow941** [comment]
This issue will close now with no possible way to fix, but still pin this at this time.
